
transfer.page.size: 3000  # 单次批量插入条数

spring:
 # 数据源配置
  datasource:
    source-db: #数据源1 ——来源数据库
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@1270.0.1:1521/ora11g
      username: root # 用户名
      password: root123 # 密码
    target-db: # 数据源2 ——目标数据库
      driver-class-name: com.mysql.jdbc.Driver # mysql的驱动你可以配置别的关系型数据库
      jdbc-url: jdbc:mysql://1270.0.1:6446/test#数据源地址
      username: test # 用户名
      password: test!123 # 密码

logging:
  config: classpath:logback-spring.xml
  level:
    com.reven.transfer.dao: info
    